### ISSUE TITLE
How to cite the DOI in papers?

### ISSUE THREAD

**Issue by shaou77** [alistairewj/mechanical-power#2]
Thanks for your sharing of the codes, which helps me a lot.  I used your code to calculate the SOFA scores in my paper. I notice you updated the "readme" and said, "If using this code, please cite the above DOI as follows". I am a newbie in writing papers, I would cite the relevant article but I don't know how to quote this “Johnson, Alistair E W, Rodrigo O. Deliberato, Art S. Neto. alistairewj/mechanical-power: Mechanical Power v1.0.0. Zenodo. DOI: 10.5281/zenodo.3263855”.  I even don't know how to import it to my endnote. 
Could you give me more information about the citation? Thanks a lot.

**Comment by alistairewj** [comment]
There are two citations in the README, a direct citation for the software (using Zenodo) and a citation for the paper which describes the analysis done with the software. For clarity it makes sense to cite both.

If you are unsure how to format a citation, you can copy the DOI and use https://crosscite.org/
That will format it into a number of different styles. If endnote can import bibtex, then one option is to format it as bibtex and import that into endnote.

**Comment by shaou77** [comment]
Thank you for your answer, you are so kind. ☺

**Comment by alistairewj** [comment]
No worries!
