### ISSUE TITLE
Where could I find the 'eicu_northwell/vent' folder?

### ISSUE THREAD

**Issue by shaou77** [alistairewj/mechanical-power#3]
Dear alistairewj:  
        I consulted you several months ago, thanks to your kindness, I submitted my papers recently. When I studied your code in this project, I found below in the readme.md which in the eicu folder：
> Run ventilation queries:
\cd ../eicu-northwell/vent
\i pivoted-vent-rc.sql
\i pivoted-vent-nc.sql
\i load-labels-od.sql
\i load-labels-vm.sql
\cd ../ventduration
\i vent-events.sql
\i ventilation-durations.sql
\cd ../../mechanical-power/eicu
> 
But I could not find the folder and these sql files in github.  Could you tell me where I can find them, or they were just files not suitable for sharing?
Thank you.

**Comment by alistairewj** [comment]
These are not public yet as they use unreleased data. We are working on releasing this data before making the code public.

**Comment by shaou77** [comment]
OK. Thank you and thanks for your released data and code, it helps me a lot. Wish you have a nice day.

**Comment by XiangBu** [comment]
hi, alistairewj, I recently began using eicu and mimic iv data in bigquery. I'd like to ask if the data of eicu is complete or still partly-public like you mentioned above, thanks!

**Comment by alistairewj** [comment]
Still partly public, and I'm not sure when it will be updated since I'm no longer working on it unfortunately!

**Comment by XiangBu** [comment]
Thanks for your reply! Thanks for your excellent work and sharing!
