### ISSUE TITLE
Some items that may refer to vent settings are not included

### ISSUE THREAD

**Issue by qinyu-zhao** [alistairewj/mechanical-power#4]
Hi,

Thank you for the SQL codes you share on GitHub. 

But when running these codes, we found that there were some items that might be relevant to mechanical ventilation were ignored.

For instance, items with id in (687,688,690,691,692,224829,224830,224864,225590,227130) have labels containing "Trach". If we understand correctly, you used these items to exclude trach. However, items with id in (940, 1022, 1832, 1948, 1020, 4441) may also refer to trach but they were excluded. 

In a similar way, items (1096,1227, 5964,6349,6350,6489,6601,6924,  6943,6985,7534,7802,7803,8053,8345,8357, 224699) are all labeled as 'PEEP', but were not included.  We haven't examined every part of codes.

We believe that you are much more familiar than us with MIMIC database. So we are wondering if these items were excluded for some reasons we don't know. 

It would be appreciated if you could answer us.

**Comment by sucaper** [comment]
We also find the same problem.

**Comment by alistairewj** [comment]
There are quite a few `itemid` which aren't frequently used to document data, for example the PEEP items:

```sql
SELECT di.label, ce.itemid, count(*)
FROM `physionet-data.mimiciii_clinical.chartevents` ce
inner join `physionet-data.mimiciii_clinical.d_items` di
on ce.itemid = di.itemid
where ce.itemid in (1096,1227, 5964,6349,6350,6489,6601,6924, 6943,6985,7534,7802,7803,8053,8345,8357, 224699)
group by 1, 2
```

Row | label | itemid | number of measurements |  
-- | -- | -- | -- | --
1 | Sigh peep level | 8345 | 10 |  
2 | Autopeep | 5964 | 2 |  
3 | Auto-PEEP level | 1096 | 2 |  
4 | auto-peep | 6489 | 5 |  
5 | total PeeP | 6350 | 1 |  
6 | Auto PeeP | 6601 | 1 |  
7 | Sigh PEEP level | 6985 | 16 |  
8 | AUTOPeeP | 6349 | 1 |  
9 | high peep | 7802 | 6 |  
10 | LOW PEEP | 6943 | 6 |  
11 | MEASURED PEEP | 6924 | 17 |  
12 | autopeep | 1227 | 14 |  
13 | low peep | 7803 | 5 |  
14 | Sigh Peep | 8357 | 7 |  
15 | Intrinsic peep | 7534 | 1 |  
16 | SIGH PEEP LEVEL | 8053 | 1

Some of these are also slightly different as well e.g. auto PEEP != set PEEP. For our study, we chose not to include these. If you correctly parsed them, you could include them, but it may not be worth the effort for such a small number of measurements.

Alternatively, for the trach measurements, you are right that we could have used those `itemid` for trach care. My belief is that all the patients who received documentation about trach care also received documentation in the `itemid` we did use, so I don't think it will change the cohort.

**Comment by qinyu-zhao** [comment]
Thank you for your prompt reply! We learned a lot from your work.
